### ISSUE TITLE
"aws-codesuite-backend-plugin-for-backstage: Not found"

### ISSUE THREAD

**Issue by catherinegomes** [awslabs/aws-codesuite-plugins-for-backstage#35]
Hi, I'm running a local deployment of backstage (per their Getting Started docs) and unable to install this plugin. Any guidance is appreciated as I've tried the following methods with the same 'plugin not found error':

From the root app:
`yarn workspace backend add @aws/aws-codesuite-backend-plugin-for-backstage`

From the packages/backend dir:
`yarn add @aws/aws-codesuite-backend-plugin-for-backstage`

From the root app:
`yarn add @aws/aws-codesuite-backend-plugin-for-backstage -W`

macOS:
  Ventura 13.1

Processor:
  Intel

Yarn version: 
  1.22.19

Node version: 
  18.12.1

Platform: 
  darwin x64

Trace: 
```
  Error: https://registry.yarnpkg.com/@aws%2faws-codesuite-backend-plugin-for-backstage: Not found
      at params.callback [as _callback] (/usr/local/lib/node_modules/yarn/lib/cli.js:66145:18)
      at self.callback (/usr/local/lib/node_modules/yarn/lib/cli.js:140890:22)
      at Request.emit (node:events:513:28)
      at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:141862:10)
      at Request.emit (node:events:513:28)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:627:28)
      at IncomingMessage.emit (node:events:525:35)
      at endReadableNT (node:internal/streams/readable:1359:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

npm manifest: 
```
  {
    "name": "backend",
    "version": "0.0.0",
    "main": "dist/index.cjs.js",
    "types": "src/index.ts",
    "private": true,
    "backstage": {
      "role": "backend"
    },
    "scripts": {
      "start": "backstage-cli package start",
      "build": "backstage-cli package build",
      "lint": "backstage-cli package lint",
      "test": "backstage-cli package test",
      "clean": "backstage-cli package clean",
      "build-image": "docker build ../.. -f Dockerfile --tag backstage"
    },
    "dependencies": {
      "@backstage/backend-common": "^0.17.0",
      "@backstage/backend-tasks": "^0.4.0",
      "@backstage/catalog-client": "^1.2.0",
      "@backstage/catalog-model": "^1.1.4",
      "@backstage/config": "^1.0.5",
      "@backstage/plugin-app-backend": "^0.3.39",
      "@backstage/plugin-auth-backend": "^0.17.2",
      "@backstage/plugin-auth-node": "^0.2.8",
      "@backstage/plugin-catalog-backend": "^1.6.0",
      "@backstage/plugin-catalog-backend-module-github": "^0.2.2",
      "@backstage/plugin-permission-common": "^0.7.2",
      "@backstage/plugin-permission-node": "^0.7.2",
      "@backstage/plugin-proxy-backend": "^0.2.33",
      "@backstage/plugin-scaffolder-backend": "^1.9.0",
      "@backstage/plugin-search-backend": "^1.2.0",
      "@backstage/plugin-search-backend-module-pg": "^0.5.0",
      "@backstage/plugin-search-backend-node": "^1.1.0",
      "@backstage/plugin-techdocs-backend": "^1.5.0",
      "@roadiehq/backstage-plugin-aws-auth": "^0.4.2",
      "app": "link:../app",
      "better-sqlite3": "^7.5.0",
      "dockerode": "^3.3.1",
      "express": "^4.17.1",
      "express-promise-router": "^4.1.0",
      "pg": "^8.3.0",
      "winston": "^3.2.1"
    },
    "devDependencies": {
      "@backstage/cli": "^0.22.0",
      "@types/dockerode": "^3.3.0",
      "@types/express": "^4.17.6",
      "@types/express-serve-static-core": "^4.17.5",
      "@types/luxon": "^2.0.4"
    },
    "files": [
      "dist"
    ]
  }
```

**Comment by niallthomson** [comment]
Hey @catherinegomes you beat us to it! We'll be publishing the NPM packages in the next couple of days and I'll update this issue when thats happened.

**Comment by niallthomson** [comment]
The first version of the plugins have been published to NPM and the reference documentation should now be reflective of you expected experience. Please raise any further issues separately. Thanks!
